---
title: "R Notebook"
output: html_notebook
---
**Load libraries**
```{r load Libraries, message=FALSE}
if (!require("here", quietly = TRUE)) install.packages("here")
if (!require("gdata", quietly = TRUE)) install.packages("gdata")
```

**Read input files**
```{r}
phenodata <- read.delim(here('data', "phenodata.txt"))

countspearson <- read.delim(here('results','gene_counts_batch-effect_correction_Adults-Children_UK_Gambia_UK-ICL_AgesBatch1_scBatch_pearson.txt'))

#countscombat <- read.delim(here('results','gene_counts_batch-effect_correction_Adults-Children_UK_Gambia_UK-ICL_AgesBatch1_Combat-seq.txt'))

countsfpkm <- read.delim(here('results','FPKM_merged_datasets_children_adults_older.txt'))

counts_fpkmhk <- read.delim(here("data",
                  "FPKM_merged_datasets_children_adults_older_normalized_by_housekeeping.tsv"))

cpm <- read.delim(here("results","CPM_merged_datasets_children_adults_elderly.txt"))
tpm <- read.delim(here("results","TPM_merged_datasets_children_adults_elderly.txt"))
fpkm <- read.delim(here("results","FPKM_merged_datasets_children_adults_elderly.txt"))


```

**Prepare datasets**
```{r}
genenames = countspearson[,1:2]

#rownames(countscombat) <- countscombat$Symbol
#countscombat = edgeR::cpm(countscombat[,-1]) # Normalization with CPM
#countscombat = as.data.frame(t(countscombat))
#countscombat$label = rownames(countscombat)
#countscombat = merge(phenodata, countscombat, by='label')
#countscombat$Group <- relevel(countscombat$Group, "Children")
countspearson <- countspearson[,colnames(countspearson) %in% colnames(countsfpkm)]
rownames(countspearson) <- countspearson$ID
countspearson <- as.data.frame(t(countspearson[,-c(1:2)]))
countspearson$label <- rownames(countspearson)
countspearson <- merge(phenodata, countspearson, by='label')
countspearson$Group <- relevel(countspearson$Group, "Children")

rownames(countsfpkm) <- countsfpkm$ID
countsfpkm <- as.data.frame(t(countsfpkm[,-c(1:2)]))
countsfpkm$label <- rownames(countsfpkm)
countsfpkm <- merge(phenodata, countsfpkm, by='label')
countsfpkm$Group <- relevel(countsfpkm$Group, "Children")

counts_fpkmhk <- merge(countsfpkm[,1:2], counts_fpkmhk, by.x = 'nameofG', by.y = 'Symbol')
rownames(counts_fpkmhk) <- counts_fpkmhk$ID
counts_fpkmhk <- as.data.frame(t(counts_fpkmhk[,-c(1:2)]))
#remove older not baseline
counts_fpkmhk <- counts_fpkmhk[rownames(counts_fpkmhk) %in% colnames(countsfpkm[,-c(1:2)]),]

counts_fpkmhk$label <- rownames(counts_fpkmhk)
counts_fpkmhk <- merge(phenodata, counts_fpkmhk, by='label',all=F)
counts_fpkmhk$Group <- relevel(counts_fpkmhk$Group, "Children")

select_sample <- c('ages_batch1',"UK_cur", "UK_ICL_cur")
counts_fpkmhk <- counts_fpkmhk[counts_fpkmhk$Sample %in% select_sample,]

rownames(cpm) <- cpm$ID
cpm <- as.data.frame(t(cpm[,-c(1:2)]))
cpm$label <- rownames(cpm)
cpm <- merge(phenodata, cpm, by='label')
cpm$Group <- relevel(cpm$Group, "Children")
cpm <- cpm[cpm$sampling.method =="curettage",]

rownames(tpm) <- tpm$ID
tpm <- as.data.frame(t(tpm[,-c(1:2)]))
tpm$label <- rownames(tpm)
tpm <- merge(phenodata, tpm, by='label')
tpm$Group <- relevel(tpm$Group, "Children")
tpm <- tpm[tpm$sampling.method =="curettage",]

rownames(fpkm) <- fpkm$ID
fpkm <- as.data.frame(t(fpkm[,-c(1:2)]))
fpkm$label <- rownames(fpkm)
fpkm <- merge(phenodata, fpkm, by='label')
fpkm$Group <- relevel(fpkm$Group, "Children")
fpkm <- fpkm[fpkm$sampling.method =="curettage",]


## Filter
#percentage_samples = 0.5
#cpm.threshold = 1
#keepcombat = colSums(countscombat[,-c(1:3)] > cpm.threshold) > 427*percentage_samples
#keeppearson = colSums(countspearson[,-c(1:3)] > cpm.threshold) > 427*percentage_samples 

#keep = keepcombat & keeppearson

#x = c(TRUE, TRUE, TRUE)
#names(x) = c('label',"Sample","Group")
#keep = c(x,keep)

#countscombat <- countscombat[,keep]
#countspearson <-  countspearson[,keep]
countspearson <- countspearson[,colnames(countspearson) %in% colnames(countsfpkm)]
```

```{r}
#Calculate log2FC based on gene expression median 
fc <- function(x){
  out <- NULL
  for(i in 1:ncol(x)) {
    adults_children <- log2(x["Adults",i]/x["Children",i])
    elderly_children <- log2(x["Elderly",i]/x["Children",i])
    elderly_adults <- log2(x["Elderly",i]/x["Adults",i])
    
    gene <- rbind(adults_children, elderly_children,elderly_adults)
    colnames(gene) <- colnames(x)[i]
    
    out <- cbind(out, gene)
  }
  return(out)
}

#countscombat.kt  = apply(countscombat[,-c(1:3)], 2, 
                         #function(x) kruskal.test(x,countscombat[,3])$p.value)
#countscombat.pwt = apply(countscombat[,-c(1:3)], 2, 
                         #function(x)  unmatrix(pairwise.wilcox.test(x,countscombat[,3], #p.adjust.method = "BH")$p.value))

#countscombat.pwt = countscombat.pwt[-3,]

##CPM
#Pairwise Wilcoxon test
cpm.pwt <- apply(cpm[,-c(1:5)], 2, 
                         function(x)  unmatrix(pairwise.wilcox.test(x, cpm[,3], p.adjust.method = "BH", exact=F)$p.value))

cpm.pwt <- cpm.pwt[-3,]

#Gene expression median by groups (CHildren, Adults, Older)
cpm.median <- apply(cpm[,-c(1:5)], 2, function (x) tapply(x, cpm$Group, median))

#log2FC
cpm.foldchange <- fc(cpm.median)

cpm.stat <- rbind(cpm.median, cpm.foldchange, cpm.pwt)

rownames(cpm.stat) <- c("CPM_Children", "CPM_Adults", "CPM_Elderly",
                               "CPM_log2FC_Adults:Children", "CPM_log2FC_Elderly:Children",
                               "CPM_log2FC_Elderly:Adults",'CPM_Wilcox_Adults:Children_pv',
                               'CPM_Wilcox_Elderly:Children_pv', 'CPM_Wilcox_Elderly:Adults_pv')

##TPM
#Pairwise Wilcoxon test
tpm.pwt <- apply(tpm[,-c(1:5)], 2, 
                         function(x)  unmatrix(pairwise.wilcox.test(x, tpm[,3], p.adjust.method = "BH", exact=F)$p.value))

tpm.pwt <- tpm.pwt[-3,]

#Gene expression median by groups (CHildren, Adults, Older)
tpm.median <- apply(tpm[,-c(1:5)], 2, function (x) tapply(x, tpm$Group, median))

#log2FC
tpm.foldchange <- fc(tpm.median)

tpm.stat <- rbind(tpm.median, tpm.foldchange, tpm.pwt)

rownames(tpm.stat) <- c("TPM_Children", "TPM_Adults", "TPM_Elderly",
                               "TPM_log2FC_Adults:Children", "TPM_log2FC_Elderly:Children",
                               "TPM_log2FC_Elderly:Adults",'TPM_Wilcox_Adults:Children_pv',
                               'TPM_Wilcox_Elderly:Children_pv', 'TPM_Wilcox_Elderly:Adults_pv')

##FPKM
#Pairwise Wilcoxon test
fpkm.pwt <- apply(fpkm[,-c(1:5)], 2, 
                         function(x)  unmatrix(pairwise.wilcox.test(x, fpkm[,3], p.adjust.method = "BH", exact=F)$p.value))

fpkm.pwt <- fpkm.pwt[-3,]

#Gene expression median by groups (CHildren, Adults, Older)
fpkm.median <- apply(fpkm[,-c(1:5)], 2, function (x) tapply(x, fpkm$Group, median))

#log2FC
fpkm.foldchange <- fc(fpkm.median)

fpkm.stat <- rbind(fpkm.median, fpkm.foldchange, fpkm.pwt)

rownames(fpkm.stat) <- c("FPKM_Children", "FPKM_Adults", "FPKM_Elderly",
                               "FPKM_log2FC_Adults:Children", "FPKM_log2FC_Elderly:Children",
                               "FPKM_log2FC_Elderly:Adults",'FPKM_Wilcox_Adults:Children_pv',
                               'FPKM_Wilcox_Elderly:Children_pv', 'FPKM_Wilcox_Elderly:Adults_pv')



out <- as.data.frame(t(rbind(cpm.stat, tpm.stat, fpkm.stat)))

#add ensemblID
out$ID <- rownames(out)

#add geneSymbol
z <- merge(cpm[,1:2], out, by = 'ID')

write.table(z, here('results','log2FC_CPM_TPM_FPKM_curretage_samples.txt'),
            sep='\t',quote=F,row.names=F)




#### FPKM adjusted
#Kruskal Wallis test
counts_fpkmhk.kt  <- apply(counts_fpkmhk[,-c(1:3)], 2, 
                         function(x) kruskal.test(x,counts_fpkmhk[,3])$p.value)
#Pairwise Wilcoxon test
counts_fpkmhk.pwt <- apply(counts_fpkmhk[,-c(1:3)], 2, 
                         function(x)  unmatrix(pairwise.wilcox.test(x,counts_fpkmhk[,3], p.adjust.method = "BH", exact=F)$p.value))

counts_fpkmhk.pwt <- counts_fpkmhk.pwt[-3,]

#Gene expression median by groups (CHildren, Adults, Older)
counts_fpkmhk.median <- apply(counts_fpkmhk[,-c(1:3)], 2, function (x) tapply(x, counts_fpkmhk$Group, median))

#log2FC
counts_fpkmhk.foldchange <- fc(counts_fpkmhk.median)



#### FPKM
#Kruskal Wallis test
countsfpkm.kt  <- apply(countsfpkm[,-c(1:3)], 2, 
                         function(x) kruskal.test(x,countsfpkm[,3])$p.value)
#Pairwise Wilcoxon test
countsfpkm.pwt <- apply(countsfpkm[,-c(1:3)], 2, 
                         function(x)  unmatrix(pairwise.wilcox.test(x,countsfpkm[,3], p.adjust.method = "BH")$p.value))

countsfpkm.pwt <- countsfpkm.pwt[-3,]

#Gene expression median by groups (CHildren, Adults, Older)
countsfpkm.median <- apply(countsfpkm[,-c(1:3)], 2, function (x) tapply(x, countsfpkm$Group, median))

#log2FC
countsfpkm.foldchange <- fc(countsfpkm.median)

#### scBatch Pearson
#Kruskal Wallis test
countspearson.kt  <- apply(countspearson[,-c(1:3)], 2, 
                         function(x) kruskal.test(x,countspearson[,3])$p.value)
#Pairwise Wilcoxon test
countspearson.pwt <- apply(countspearson[,-c(1:3)], 2, 
                         function(x)  unmatrix(pairwise.wilcox.test(x,countspearson[,3], p.adjust.method = "BH")$p.value))

countspearson.pwt <- countspearson.pwt[-3,]

#Gene expression median by groups (CHildren, Adults, Older)
countspearson.median <- apply(countspearson[,-c(1:3)], 2, function (x) tapply(x, countspearson$Group, median))

#log2FC
countspearson.foldchange <- fc(countspearson.median)

#countscombat.stat = rbind(countscombat.kt, countscombat.pwt)


#Join results FPKM adjusted
counts_fpkmhk.stat <- rbind(counts_fpkmhk.kt, counts_fpkmhk.pwt,
                        counts_fpkmhk.median, counts_fpkmhk.foldchange)


#Join results FPKM
countsfpkm.stat <- rbind(countsfpkm.kt, countsfpkm.pwt,
                        countsfpkm.median, countsfpkm.foldchange)

#Join results scBatch Pearson
countspearson.stat <- rbind(countspearson.kt, countspearson.pwt, 
                           countspearson.median, countspearson.foldchange)

#rename rows
rownames(counts_fpkmhk.stat) <- c('FPKM_KW_pv', 'FPKM_Wilcox_Adults:Children_pv',
                               'FPKM_Wilcox_Older:Children_pv', 'FPKM_Wilcox_Older:Adults_pv',
                               "FPKM_Children", "FPKM_Adults", "FPKM_Older",
                               "FPKM_log2FC_Adults:Children", "FPKM_log2FC_Older:Children",
                               "FPKM_log2FC_Older:Adults")


#rename rows
rownames(countsfpkm.stat) <- c('FPKM_KW_pv', 'FPKM_Wilcox_Adults:Children_pv',
                               'FPKM_Wilcox_Older:Children_pv', 'FPKM_Wilcox_Older:Adults_pv',
                               "FPKM_Children", "FPKM_Adults", "FPKM_Older",
                               "FPKM_log2FC_Adults:Children", "FPKM_log2FC_Older:Children",
                               "FPKM_log2FC_Older:Adults")
#rename rows
rownames(countspearson.stat) <- c('scBatch_KW_pv', 'scBatch_Wilcox_Adults:Children_pv',
                                 'scBatch_Wilcox_Older:Children_pv',
                                 'scBatch_Wilcox_Older:Adults_pv',
                               "scBatch_Children", "scBatch_Adults", "scBatch_Older",
                               "scBatch_log2FC_Adults:Children", "scBatch_log2FC_Older:Children",
                               "scBatch_log2FC_Older:Adults")

#out = as.data.frame(t(rbind(countscombat.stat, countspearson.stat)))
#Join FPKM norm and scBatch Pearson
#out <- as.data.frame(t(rbind(countsfpkm.stat, countspearson.stat)))
out <- as.data.frame(t(counts_fpkmhk.stat))

#add ensemblID
out$ensemblID <- rownames(out)

#add geneSymbol
z <- merge(genenames, out, by.x = 'ID', by.y = 'ensemblID', all=F)

write.table(z, here('results','Kruskal-Wallis_test_log2FC_FPKM_adjusted_by_housekeeping-genes_only_curretage_samples.txt'),
            sep='\t',quote=F,row.names=F)

```

