---
title: "R Notebook"
output: html_notebook
---

```{r Load libraries, message=F}
if(!require(here, quietly = F)) {
  install.packages("here") 
  library(here)
}

if(!require(tidyverse, quietly = F)) {
  install.packages("tidyverse")
  library(tidyverse)
}

if(!require(edgeR, quietly = T)) {BiocManager::install("edgeR")}
if(!require(RUVSeq, quietly = T)) BiocManager::install("RUVSeq")
if(!require(mdp, quietly = T)) BiocManager::install("mdp")
```

```{r}
#Raw counts file
counts <- read.delim(here("data","gene_counts_merged_datasets_children_adults_elderly.txt"))

#Raw counts corrected with Combat-seq
#counts <- read.delim(here("results","gene_counts_batch-effect_correction_Adults-Children_UK_Gambia_UK-ICL_AgesBatch1_Combat-seq_with_nameofG.txt"))

#Raw counts corrected with Combat-seq curettage
#counts <- read.delim(here("data","gene_counts_merged_datasets_children_adults_elderly_curettage_Combat-seq.tsv"))

phenodata <- read.delim(here("data", "sample_information.txt"))
phenodata_curettage <- read.delim(here("data","phenodata_curettage.tsv"))
tmm <- read.delim(here("data", "tmm_counts_curettage.tsv"))
tpm <- read.delim(here("results", "TPM_merged_datasets_children_adults_elderly.txt"))

degs <- read.delim(here("data","diff_expression_byAge_bySex_curettage.tsv"))
```


```{r Subset}
phenodata <- phenodata[phenodata$timepoint == "baseline" & 
                       phenodata$sampling.method == "curettage",]

phenodata$Group <- factor(phenodata$Group, c("Children","Adults","Older"))

hgnc <- counts[,1:2]

rownames(counts) <- counts$ID

# MDP analysis
subcounts <- subset(counts, select = as.vector(phenodata$label))
keep <- rowSums(subcounts > 5) > ncol(subcounts)*0.3
subcounts <- subcounts[keep,]

mdp.results <- mdp(data = as.data.frame(cpm(subcounts)), 
                   pdata = data.frame(Sample = phenodata$label, Class = phenodata$Group),
                   control_lab = "Children")

samplescore <- mdp.results$sample_scores$allgenes
 
samples2drop <- subset(samplescore, 
                       Score > min(samplescore[samplescore$Class == "Older",2]) & 
                         Class != "Older")

# Remove samples based on MDP analysis
phenodata <- subset(phenodata, !(label %in% as.vector(samples2drop$Sample)))
counts <- subset(counts, select = as.vector(phenodata$label))
```

```{r Diff expression analysis with RUVseq}
df <- NULL

for(i in levels(phenodata$Group)) {
  for(j in levels(phenodata$sex)) {
    
    subphenodata <- phenodata[phenodata$Group != i & phenodata$sex == j,]    
    subphenodata$Group <- factor(subphenodata$Group, as.vector(unique(subphenodata$Group)))
    
    subcounts <- subset(counts, select = as.vector(subphenodata$label))
    
    #Filter low expression genes
    keep <- rowSums(subcounts > 5) > ncol(subcounts)*0.3
    subcounts <- subcounts[keep,]
    
    subhgnc <- hgnc[hgnc$ID %in% rownames(subcounts),]
    
    ncounts <- newSeqExpressionSet(as.matrix(subcounts),
                                   phenoData = data.frame(Group = subphenodata$Group,
                                                          row.names=subphenodata$label))
    
    ### Empirical stable genes
    design <- model.matrix(~Group, data=pData(ncounts))
    y <- DGEList(counts=counts(ncounts), group=subphenodata$Group)
    y <- calcNormFactors(y, method="upperquartile")
    y <- estimateGLMCommonDisp(y, design)
    y <- estimateGLMTagwiseDisp(y, design)
    fit <- glmFit(y, design)
    lrt <- glmLRT(fit, coef=2)
    top <- topTags(lrt, n=nrow(ncounts))$table
    empirical <- rownames(ncounts)[which(!(rownames(ncounts) %in% rownames(top)[1:5000]))]
    ###
    
    ncounts <- betweenLaneNormalization(ncounts, which="upper")
    
    set1 <- RUVg(ncounts, empirical, k=1)
    
    design <- model.matrix(~Group + W_1, data=pData(set1))
    
    y <- DGEList(counts = subcounts, genes = subhgnc, group = subphenodata$Group)
    y <- calcNormFactors(y)
    y <- estimateGLMCommonDisp(y, design)
    y <- estimateGLMTagwiseDisp(y, design)
    fit <- glmFit(y, design, robust=T)
    degs <- topTags(glmLRT(fit, coef=2), n=NULL)$table
    
    ndown <- nrow(degs[degs$logFC < -1 & degs$FDR <0.01,])
    nup <- nrow(degs[degs$logFC > 1 & degs$FDR <0.01,])
    
    filename <- paste0("DEGs_", levels(subphenodata$Group)[1], ".vs.", 
                       levels(subphenodata$Group)[2], ".sex_",j,"_glmLRT_RUVg_empirical_control.tsv")
    
    write.table(degs, here("results", "diff_express_edgeR" ,filename),
                sep='\t',quote=F,row.names = F)
    
    df <- rbind(df, data.frame(ref = levels(subphenodata$Group)[1], 
                               tret= levels(subphenodata$Group)[2],
                               sex = j, Up = nup, Down = ndown))
  }
}

write.table(df, here("results", "diff_express_edgeR" ,"number_DEGS_logFC1_fdr0.01_glmLRT_RUVg_empirical_control.txt"),
                sep='\t',quote=F,row.names = F)
``` 


```{r Standard Diff expression analysis}
design <- model.matrix(~0 + Group:sex, data=phenodata)
    
y <- DGEList(counts = counts, genes = hgnc,
             group = interaction(phenodata$Group, phenodata$sex))

keep <- filterByExpr(y)
y <- y[keep, , keep.lib.sizes=FALSE]

y <- calcNormFactors(y)
y <- estimateGLMCommonDisp(y, design)
y <- estimateGLMTagwiseDisp(y, design)
fit <- glmQLFit(y, design, robust=TRUE)

adults.vs.children.f <- topTags(glmQLFTest(fit, contrast=c(-1,1,0,0,0,0)),
                                n=NULL)$table

elderly.vs.adults.f <- topTags(glmQLFTest(fit, contrast=c(0,-1,1,0,0,0)),
                               n=NULL)$table

elderly.vs.children.f <- topTags(glmQLFTest(fit, contrast=c(-1,0,1,0,0,0)),
                                 n=NULL)$table

adults.vs.children.m <- topTags(glmQLFTest(fit, contrast=c(0,0,0,-1,1,0)),
                                n=NULL)$table

elderly.vs.adults.m <- topTags(glmQLFTest(fit, contrast=c(0,0,0,0,-1,1)),
                               n=NULL)$table

elderly.vs.children.m <- topTags(glmQLFTest(fit, contrast=c(0,0,0,-1,0,1)),
                                 n=NULL)$table

m.vs.f.children <- topTags(glmQLFTest(fit, contrast=c(-1,0,0,1,0,0)),
                                 n=NULL)$table
m.vs.f.adults <- topTags(glmQLFTest(fit, contrast=c(0,-1,0,0,1,0)),
                                 n=NULL)$table
m.vs.f.elderly <- topTags(glmQLFTest(fit, contrast=c(0,0,-1,0,0,1)),
                                 n=NULL)$table

out <- adults.vs.children.f %>%
  full_join(adults.vs.children.m, by = c("ID","nameofG"), suffix = c(".Adults.vs.Children.F", ".Adults.vs.Children.M")) %>%
  full_join(elderly.vs.children.f, by = c("ID","nameofG")) %>%
  full_join(elderly.vs.children.m, by = c("ID","nameofG"), suffix = c(".Elderly.vs.Children.F", ".Elderly.vs.Children.M")) %>%
  full_join(elderly.vs.adults.f, by = c("ID","nameofG")) %>%
  full_join(elderly.vs.adults.m, by = c("ID","nameofG"), suffix = c(".Elderly.vs.Adults.F", ".Elderly.vs.Adults.M")) %>%
  full_join(m.vs.f.children, by = c("ID","nameofG")) %>%
  full_join(m.vs.f.adults, by = c("ID","nameofG"), suffix = c(".M.vs.F.Children", ".M.vs.F.Adults")) %>%
  full_join(dplyr::rename(m.vs.f.elderly, logFC.M.vs.F.Elderly = logFC, logCPM.M.vs.F.Elderly = logCPM, F.M.vs.F.Elderly = F, PValue.M.vs.F.Elderly = PValue, FDR.M.vs.F.Elderly = FDR), by = c("ID","nameofG"))


up.elderly.vs.children.f <- nrow(elderly.vs.children.f[elderly.vs.children.f$logFC > 1 &
                                                         elderly.vs.children.f$FDR < 0.01,])
down.elderly.vs.children.f <- nrow(elderly.vs.children.f[elderly.vs.children.f$logFC < -1 &
                                                         elderly.vs.children.f$FDR < 0.01,])
up.elderly.vs.children.m <- nrow(elderly.vs.children.m[elderly.vs.children.m$logFC > 1 &
                                                         elderly.vs.children.m$FDR < 0.01,])
down.elderly.vs.children.m <- nrow(elderly.vs.children.m[elderly.vs.children.m$logFC < -1 &
                                                         elderly.vs.children.m$FDR < 0.01,])

up.elderly.vs.adults.f <- nrow(elderly.vs.adults.f[elderly.vs.adults.f$logFC > 1 &
                                                         elderly.vs.adults.f$FDR < 0.01,])
down.elderly.vs.adults.f <- nrow(elderly.vs.adults.f[elderly.vs.adults.f$logFC < -1 &
                                                         elderly.vs.adults.f$FDR < 0.01,])
up.elderly.vs.adults.m <- nrow(elderly.vs.adults.m[elderly.vs.adults.m$logFC > 1 &
                                                         elderly.vs.adults.m$FDR < 0.01,])
down.elderly.vs.adults.m <- nrow(elderly.vs.adults.m[elderly.vs.adults.m$logFC < -1 &
                                                         elderly.vs.adults.m$FDR < 0.01,])

up.adults.vs.children.f <- nrow(adults.vs.children.f[adults.vs.children.f$logFC > 1 &
                                                         adults.vs.children.f$FDR < 0.01,])
down.adults.vs.children.f <- nrow(adults.vs.children.f[adults.vs.children.f$logFC < -1 &
                                                         adults.vs.children.f$FDR < 0.01,])
up.adults.vs.children.m <- nrow(adults.vs.children.m[adults.vs.children.m$logFC > 1 &
                                                         adults.vs.children.m$FDR < 0.01,])
down.adults.vs.children.m <- nrow(adults.vs.children.m[adults.vs.children.m$logFC < -1 &
                                                         adults.vs.children.m$FDR < 0.01,])

up.m.vs.f.children <- nrow(m.vs.f.children[m.vs.f.children$logFC > 1 &
                                             m.vs.f.children$FDR < 0.01,])
down.m.vs.f.children <- nrow(m.vs.f.children[m.vs.f.children$logFC < -1 &
                                             m.vs.f.children$FDR < 0.01,])
up.m.vs.f.adults <- nrow(m.vs.f.adults[m.vs.f.adults$logFC > 1 &
                                             m.vs.f.adults$FDR < 0.01,])
down.m.vs.f.adults <- nrow(m.vs.f.adults[m.vs.f.adults$logFC < -1 &
                                             m.vs.f.adults$FDR < 0.01,])
up.m.vs.f.elderly <- nrow(m.vs.f.elderly[m.vs.f.elderly$logFC > 1 &
                                             m.vs.f.elderly$FDR < 0.01,])
down.m.vs.f.elderly <- nrow(m.vs.f.elderly[m.vs.f.elderly$logFC < -1 &
                                             m.vs.f.elderly$FDR < 0.01,])


compar <- c(rep(c("Adults.vs.Children"),2), 
            rep(c("Elderly.vs.Children"),2), 
            rep(c("Elderly.vs.Adults"),2),
            rep(c("M.vs.F"),3))

up <- c(up.adults.vs.children.f, up.adults.vs.children.m,
        up.elderly.vs.children.f, up.elderly.vs.children.m,
        up.elderly.vs.adults.f, up.elderly.vs.adults.m,
        up.m.vs.f.children, up.m.vs.f.adults, up.m.vs.f.elderly)

down <- c(down.adults.vs.children.f, down.adults.vs.children.m,
          down.elderly.vs.children.f, down.elderly.vs.children.m,
          down.elderly.vs.adults.f, down.elderly.vs.adults.m,
        down.m.vs.f.children, down.m.vs.f.adults, down.m.vs.f.elderly)

df <- data.frame(Comparison = compar,
                 Sex = c(rep(c("F","M"),3), c("Children","Adults","Elderly")),
                 Up = up,
                 Down = down)

#number of diff express genes 
write.table(df, here("results","diff_express_edgeR",
                     "number_DEGS_logFC1_fdr0.01_standard_v2"), 
            sep="\t",quote=F,row.names = F)

#write.table(adults.vs.children.f, here("results","diff_express_edgeR",
#                                       "DEGs_Children.vs.Adults.sex_F_standard.tsv"),
#            sep = "\t",quote=F,row.names=F)
#write.table(adults.vs.children.m, here("results","diff_express_edgeR",
#                                       "DEGs_Children.vs.Adults.sex_M_standard.tsv"),
#            sep = "\t",quote=F,row.names=F)
#write.table(elderly.vs.adults.m, here("results","diff_express_edgeR",
#                                       "DEGs_Adults.vs.Elderly.sex_M_standard.tsv"),
#            sep = "\t",quote=F,row.names=F)
#write.table(elderly.vs.adults.f, here("results","diff_express_edgeR",
#                                       "DEGs_Adults.vs.Elderly.sex_F_standard.tsv"),
#            sep = "\t",quote=F,row.names=F)
#write.table(elderly.vs.children.m, here("results","diff_express_edgeR",
#                                       "DEGs_Children.vs.Elderly.sex_M_standard.tsv"),
#            sep = "\t",quote=F,row.names=F)
#write.table(elderly.vs.children.f, here("results","diff_express_edgeR",
#                                       "DEGs_Children.vs.Elderly.sex_F_standard.tsv"),
#            sep = "\t",quote=F,row.names=F)
#write.table(m.vs.f.children, here("results","diff_express_edgeR",
#                                       "DEGs_M.vs.F.children_standard.tsv"),
#            sep = "\t",quote=F,row.names=F)
#write.table(m.vs.f.adults, here("results","diff_express_edgeR",
#                                       "DEGs_M.vs.F.adults_standard.tsv"),
#            sep = "\t",quote=F,row.names=F)
#write.table(m.vs.f.elderly, here("results","diff_express_edgeR",
#                                       "DEGs_M.vs.F.elderly_standard.tsv"),
#            sep = "\t",quote=F,row.names=F)

#write.table(out, here("results","diff_express_edgeR","diff_expression_byAge_bySex_curettage.tsv"),
#            sep='\t', quote=F, row.names=F)

#write.table(phenodata, here("data","phenodata_curettage.tsv"),sep='\t',quote=F,row.names=F)

#write.table(counts, here("data","raw_counts_curettage.tsv"),sep='\t',quote=F,row.names=F)


```


```{r Plots}
#Filter low expression genes
keep <- rowSums(counts > 5) > ncol(counts)*0.3
subcounts <- counts[keep,]

subhgnc <- hgnc[hgnc$ID %in% rownames(subcounts),]

ncounts <- newSeqExpressionSet(as.matrix(subcounts), 
                               phenoData = data.frame(Group = phenodata$Group,
                                                      row.names=phenodata$label))

### Empirical stable genes
design <- model.matrix(~Group, data=pData(ncounts))
y <- DGEList(counts=counts(ncounts), group=phenodata$Group)
y <- calcNormFactors(y, method="upperquartile")
y <- estimateGLMCommonDisp(y, design)
y <- estimateGLMTagwiseDisp(y, design)
fit <- glmFit(y, design)
lrt <- glmLRT(fit, coef=2:3)
top <- topTags(lrt, n=nrow(ncounts))$table
empirical <- rownames(ncounts)[which(!(rownames(ncounts) %in% rownames(top)[1:5000]))]
###

ncounts <- betweenLaneNormalization(ncounts, which="upper")

set1 <- RUVg(ncounts, empirical, k=1)

## Commands to save norm counts for all libraries

normcounts <- as.data.frame(t(cpm(normCounts(set1))))
normcounts$label <- rownames(normcounts)
normcounts <- merge(phenodata, normcounts, by="label")
x <- normcounts %>% 
  pivot_longer(-colnames(normcounts[,1:7]), 
               names_to = "ensemblID", values_to = "values") %>%
  left_join(hgnc, by= c("ensemblID" = "ID"))
#write.table(x, here("results",
#                    "RUVseq_adjusted_merged_datasets_children_adults_elderly_curettage.txt"), #
#            sep = "\t", quote = F, row.names=F)


#"RUVseq_adjusted_merged_datasets_children_adults_elderly_curettage.txt"))
genes <- c("ACE2","TMPRSS2","FURIN","ANPEP","DPP4","APOD","L3MBTL2","RBCK1","TMEM199","WDR55")

x %>%
  filter(nameofG %in% genes) %>%
  mutate(Group = fct_relevel(Group, "Children","Adults","Older")) %>%
  mutate(nameofG = fct_relevel(nameofG, genes)) %>%
  ggplot(aes(x = Group, y = values, fill = sex), cex=1.5) +
  geom_boxplot(position= "dodge", outlier.shape=NA) +
  facet_wrap(vars(nameofG),nrow=2) +
 # scale_y_continuous(trans='log2') +
  ylab("RUVSeq normalized counts")+
  theme_bw(base_size = 12) +
  ylim(0,350)


### TPM
rownames(tpm) <- tpm$ID
tpm <- subset(tpm, select= as.vector(phenodata$label))
tpm <- as.data.frame(t(tpm))

tpm$label <- rownames(tpm)
tpm <- merge(phenodata, tpm, by="label")
x <- tpm %>% 
  pivot_longer(-colnames(tpm[,1:7]), 
               names_to = "ensemblID", values_to = "values") %>%
  left_join(hgnc, by= c("ensemblID" = "ID"))


genes <- c("ACE2","TMPRSS2","FURIN","ANPEP","DPP4","APOD","L3MBTL2","RBCK1","TMEM199","WDR55")

x %>%
  filter(nameofG %in% genes) %>%
  mutate(Group = fct_relevel(Group, "Children","Adults","Older")) %>%
  mutate(nameofG = fct_relevel(nameofG, genes)) %>%
  ggplot(aes(x = Group, y = values, fill = sex), cex=1.5) +
  geom_boxplot(position= "dodge", outlier.shape=NA) +
  facet_wrap(vars(nameofG),nrow=2) +
 # scale_y_continuous(trans='log2') +
  ylab("TPM")+
  theme_bw(base_size = 12) +
  ylim(0,350)

## TMM
countsdge <- DGEList(counts = counts, genes = hgnc, group = phenodata$Group)

countsdge <- calcNormFactors(countsdge, method = "TMM")
tmm <- as.data.frame(cpm(countsdge))
#tmm$ID <- rownames(tmm)
#tmm <- merge(hgnc, tmm, by="ID")
tmm <- as.data.frame(t(tmm))
#write.table(tmm, here("data", "tmm_counts_curettage"), sep="\t", quote=F, row.names=F)
tmm$label <- rownames(tmm)
tmm <- merge(phenodata, tmm, by="label")
x <- tmm %>% 
  pivot_longer(-colnames(tmm[,1:7]), 
               names_to = "ensemblID", values_to = "values") %>%
  left_join(hgnc, by= c("ensemblID" = "ID"))

#genes <- c("ACE2","TMPRSS2","FURIN","ANPEP","DPP4","CTSB","CTSL","APOD","L3MBTL2","RBCK1","TMEM199","WDR55")

genes <- c("ACE2","TMPRSS2","FURIN","ANPEP","DPP4","CTSB","CTSL")

#negative controles
#genes <- c("ATP5G3","NDUFB11","UQCRFS1","COL3A1","COL1A1","COL4A5","TFRC","GOT1","NDUFB5","PTPRO","NDUFS3"	,"CRHBP","MYO5C","NDUFB6","GOT2","ATP5A1","ATP5G1","ATP5J","SDHB","SDHD")

x %>%
  filter(nameofG %in% genes) %>%
  mutate(Group = fct_relevel(Group, "Children","Adults","Older")) %>%
  mutate(nameofG = fct_relevel(nameofG, genes)) %>%
  ggplot(aes(x = Group, y = values, fill = sex), cex=1.5) +
  geom_boxplot(position= "dodge", outlier.shape=NA) +
  facet_wrap(vars(nameofG),nrow=2) +
  scale_y_continuous(trans='log2') +
  ylab("TMM normalized counts")+
  theme_bw(base_size = 12) 
  #ylim(0,350)

```

```{r TMM by group}
rownames(tmm) <- tmm$ID
tmm <- tmm[,-c(1:2)]
tmm <- as.data.frame(t(tmm))

tmm$label <- rownames(tmm)

out <- phenodata %>%
   full_join(tmm, by = "label") %>%
   pivot_longer(-colnames(df[,c(1:7)]), names_to = "genes", values_to = "values") %>%
   group_by(Group, sex, genes) %>%
   summarise(mean=mean(values)) %>%
   pivot_wider(id_cols = "genes", names_from = c("Group","sex"), values_from = "mean") %>%
   inner_join(degs, by = c("genes" = "ID")) %>%
   select(-starts_with(c("logCPM.", "F."))) %>%
   rename(ID = genes, TMM_Adults_M = Adults_M, TMM_Adults_F = Adults_F, TMM_Children_F = Children_F,
          TMM_Children_M = Children_M, TMM_Elderly_M = Older_M, TMM_Elderly_F = Older_F) %>%
   select(ID, nameofG, everything())

write.table(out, here("data","TMM_diff_expression_byAge_bySex_curettage.tsv"), sep = "\t",
            quote = F, row.names = F)
```

```{r}
adults.vs.children.f <- read.delim(here("results","diff_express_edgeR","DEGs_Children.vs.Adults.sex_F_glmLRT_RUVg_empirical_control.tsv"))
adults.vs.children.m <- read.delim(here("results","diff_express_edgeR","DEGs_Children.vs.Adults.sex_M_glmLRT_RUVg_empirical_control.tsv"))
elderly.vs.children.f <- read.delim(here("results","diff_express_edgeR","DEGs_Children.vs.Older.sex_F_glmLRT_RUVg_empirical_control.tsv"))
elderly.vs.children.m <- read.delim(here("results","diff_express_edgeR","DEGs_Children.vs.Older.sex_M_glmLRT_RUVg_empirical_control.tsv"))
elderly.vs.adults.f <- read.delim(here("results","diff_express_edgeR","DEGs_Adults.vs.Older.sex_F_glmLRT_RUVg_empirical_control.tsv"))
elderly.vs.adults.m <- read.delim(here("results","diff_express_edgeR","DEGs_Adults.vs.Older.sex_M_glmLRT_RUVg_empirical_control.tsv"))


out2 <- adults.vs.children.f %>%
  inner_join(adults.vs.children.m, by = c("ID","nameofG"), suffix = c(".Adults.vs.Children.F", ".Adults.vs.Children.M")) %>%
  inner_join(elderly.vs.children.f, by = c("ID","nameofG")) %>%
  inner_join(elderly.vs.children.m, by = c("ID","nameofG"), suffix = c(".Elderly.vs.Children.F", ".Elderly.vs.Children.M")) %>%
  inner_join(elderly.vs.adults.f, by = c("ID","nameofG")) %>%
  inner_join(elderly.vs.adults.m, by = c("ID","nameofG"), suffix = c(".Elderly.vs.Adults.F", ".Elderly.vs.Adults.M"))
  #full_join(m.vs.f.children, by = c("ID","nameofG")) %>%
  #full_join(m.vs.f.adults, by = c("ID","nameofG"), suffix = c(".M.vs.F.Children", ".M.vs.F.Adults")) %>%
  #full_join(dplyr::rename(m.vs.f.elderly, logFC.M.vs.F.Elderly = logFC, logCPM.M.vs.F.Elderly = logCPM, F.M.vs.F.Elderly = F, PValue.M.vs.F.Elderly = PValue, FDR.M.vs.F.Elderly = FDR), by = c("ID","nameofG"))

out <- out[,-c(1:2)]
out <- as.data.frame(t(out))

out$label <- rownames(out)

out3 <- phenodata %>%
   full_join(out, by = "label") %>%
   pivot_longer(-colnames(phenodata), names_to = "genes", values_to = "values") %>%
   group_by(Group, sex, genes) %>%
   summarise(mean=mean(values)) %>%
   pivot_wider(id_cols = "genes", names_from = c("Group","sex"), values_from = "mean") %>%
   inner_join(out2, by = c("genes" = "ID")) %>%
   select(-starts_with(c("logCPM.", "LR."))) %>%
   select(ID = genes, nameofG,RUVseq_Adults_M = Adults_M, RUVseq_Adults_F = Adults_F, 
          RUVseq_Children_F = Children_F, RUVseq_Children_M = Children_M, RUVseq_Elderly_M = Older_M,
          RUVseq_Elderly_F = Older_F, everything())

write.table(out3, here("data","RUVSeq_diff_expression_byAge_bySex_curettage.tsv"), sep = "\t",
            quote = F, row.names = F)


```

